parameters:
    atrapalo.inheritances.notary.distributor.class: Atrapalo\InheritancesBundle\Services\Notary\Distributor

services:
    atrapalo.inheritances.notary.distributor:
        class: "%atrapalo.inheritances.notary.distributor.class%"
